### ISSUE TITLE
Apk diff tool

### ISSUE THREAD

**Issue by RandLily** [quarkslab/diffing-portal#10]
I see that your amazing diff tool to detect modifications within an obfuscated application，https://blog.quarkslab.com/android-application-diffing-engine-overview.html
How could i get this tool？and if this tool is can't be shared，could you tell me some good idea or nice tool to diff apk?
thx!!!

**Comment by RobinDavid** [comment]
Hello @RandLily !
Ufortunately, this was more an experiment rather than a proper tool. There is nowhere to download it.

To diff apk, AFAIK, it is easier to do text-based diffing using the decompiled DEX, which you can do with jadx + meld for instance.

Closing the issue.
